variables:
    REVIEW_APP_NAME: Abdoul-Gadirou-${CI_COMMIT_REF_NAME}
    REVIEW_API_ENDPOINT: ip10-0-21-5-cntb7gbk3ds0ljk6g7g0-1993.direct.docker.labs.eazytraining.fr
    REVIEW_APP_ENDPOINT: ip10-0-21-5-cntb7gbk3ds0ljk6g7g0-80.direct.docker.labs.eazytraining.fr
    INTERNAL_PORT: 80
    EXTERNAL_PORT: 8080

.deploy review:
  image: docker:cli
  services:
   - name : docker:dind
     alias: docker
  stage: Deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://${REVIEW_APP_ENDPOINT}
    on_stop: stop review
  only:
    - merge_requests
  variables:
    APP_NAME: ${REVIEW_APP_NAME}
  script:
    - apk --no-cache add curl
    - echo $APP_NAME
    - 'curl -X POST http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'
stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
    APP_NAME: ${REVIEW_APP_NAME}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual  
  script:
    - apk --no-cache add curl
    - 'curl -X DELETE http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\"}"'