variables:
  STG_API_ENDPOINT: ip10-0-21-4-cntb7gbk3ds0ljk6g7g0-1993.direct.docker.labs.eazytraining.fr
  STG_APP_ENDPOINT: ip10-0-21-4-cntb7gbk3ds0ljk6g7g0-80.direct.docker.labs.eazytraining.fr
  INTERNAL_PORT: 80
  EXTERNAL_PORT: 80
.deploy staging:
  image: docker:cli
  services:
   - name : docker:dind
     alias: docker
  stage: Deploy staging
  environment:
    name: staging
    url: http://${STG_APP_ENDPOINT}
  only:
    - master   
  script:
    - apk --no-cache add curl
    - 'curl -X POST http://${STG_API_ENDPOINT}/staging -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

